const products = [
  // ── SHOES ──
  {
    id: 1,
    name: "On Running Cloudmonster",
    brand: "On Running",
    category: "Shoes",
    price: 185,
    colors: ["Black", "White/Gray"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    availability: { "39": 2, "40": 3, "41": 5, "42": 4, "43": 3, "44": 2, "45": 1 },
    badge: "New",
    description: "Maximum cushioning running shoe with monster-sized CloudTec® pods. Designed for long distances and everyday comfort.",
    emoji: "🖤"
  },
  {
    id: 2,
    name: "On Running Cloudswift 3",
    brand: "On Running",
    category: "Shoes",
    price: 165,
    colors: ["White", "Ice/Blue"],
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    availability: { "38": 1, "39": 3, "40": 4, "41": 5, "42": 3, "43": 2, "44": 0 },
    badge: "Hot",
    description: "Lightweight everyday trainer with CloudTec® technology for effortless speed on any surface.",
    emoji: "🤍"
  },
  {
    id: 3,
    name: "On Running Cloud X 4",
    brand: "On Running",
    category: "Shoes",
    price: 155,
    colors: ["Blue/Pink/Teal", "Black/White"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "38": 2, "39": 2, "40": 3, "41": 4, "42": 5, "43": 3, "44": 2, "45": 1 },
    badge: "Trending",
    description: "Training shoe built for gym and street. Versatile, lightweight, and incredibly responsive.",
    emoji: "💙"
  },
  {
    id: 4,
    name: "On Running Cloudsurfer 7",
    brand: "On Running",
    category: "Shoes",
    price: 175,
    colors: ["Gray/White", "White/Sage"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    availability: { "39": 1, "40": 2, "41": 4, "42": 5, "43": 4, "44": 2, "45": 1 },
    badge: "New",
    description: "Surfer-inspired running shoe that feels like a cloud with every stride.",
    emoji: "🩶"
  },
  {
    id: 5,
    name: "On Running Cloud 5 Knit",
    brand: "On Running",
    category: "Shoes",
    price: 145,
    colors: ["Black/Gray"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    availability: { "39": 2, "40": 3, "41": 3, "42": 4, "43": 2, "44": 1 },
    badge: "",
    description: "Sleek knit upper on On's iconic Cloud sole. Perfect for style and comfort.",
    emoji: "🖤"
  },
  {
    id: 6,
    name: "Nike Zoom Fly 5",
    brand: "Nike",
    category: "Shoes",
    price: 160,
    colors: ["White/Purple", "Black/Pink"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "38": 1, "39": 2, "40": 3, "41": 5, "42": 4, "43": 3, "44": 2, "45": 0 },
    badge: "Hot",
    description: "Nike's carbon-plate racing shoe built for speed. Featuring React X foam for explosive energy return.",
    emoji: "💜"
  },
  {
    id: 7,
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    category: "Shoes",
    price: 130,
    colors: ["Cream/Olive", "White/White"],
    sizes: ["39", "40", "41", "42", "43", "44", "45", "46"],
    availability: { "39": 3, "40": 4, "41": 5, "42": 5, "43": 4, "44": 3, "45": 2, "46": 1 },
    badge: "Classic",
    description: "The iconic AF1 in a premium cream/olive colorway. A true street staple.",
    emoji: "🤎"
  },
  {
    id: 8,
    name: "Nike Pegasus 41",
    brand: "Nike",
    category: "Shoes",
    price: 140,
    colors: ["Black/White", "Pink/White"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "38": 2, "39": 3, "40": 4, "41": 4, "42": 3, "43": 3, "44": 2, "45": 1 },
    badge: "",
    description: "Nike's most versatile running shoe. React foam cushioning for everyday runs.",
    emoji: "🩷"
  },
  {
    id: 9,
    name: "Adidas Ultraboost 23",
    brand: "Adidas",
    category: "Shoes",
    price: 150,
    colors: ["White/Black", "Olive/Black"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    availability: { "39": 2, "40": 3, "41": 4, "42": 5, "43": 3, "44": 2, "45": 1 },
    badge: "New",
    description: "Adidas Boost technology returns energy with every step. Primeknit upper for a sock-like fit.",
    emoji: "🖤"
  },
  {
    id: 10,
    name: "Adidas Predator Elite",
    brand: "Adidas",
    category: "Shoes",
    price: 145,
    colors: ["Olive/Black", "Black/Reflective"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    availability: { "39": 1, "40": 2, "41": 3, "42": 4, "43": 2, "44": 1, "45": 0 },
    badge: "Limited",
    description: "Fearsome traction and precision. Built for the streets as much as the pitch.",
    emoji: "🟢"
  },
  {
    id: 11,
    name: "Alexander McQueen Oversized",
    brand: "Alexander McQueen",
    category: "Shoes",
    price: 395,
    colors: ["White/Black", "White/White"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "38": 1, "39": 2, "40": 2, "41": 3, "42": 2, "43": 2, "44": 1, "45": 1 },
    badge: "Luxury",
    description: "The legendary McQ oversized sole sneaker. Premium leather upper, iconic silhouette.",
    emoji: "🤍"
  },
  {
    id: 12,
    name: "Nike Air Max 270",
    brand: "Nike",
    category: "Shoes",
    price: 135,
    colors: ["Gray/Orange"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    availability: { "39": 2, "40": 3, "41": 4, "42": 4, "43": 3, "44": 2, "45": 1 },
    badge: "",
    description: "Nike's largest Air unit yet. Maximum cushioning, modern silhouette.",
    emoji: "🧡"
  },

  // ── SLIDES ──
  {
    id: 13,
    name: "On Cloudrift Slide",
    brand: "On Running",
    category: "Slides",
    price: 95,
    colors: ["Black", "White", "Yellow"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "38": 3, "39": 4, "40": 5, "41": 5, "42": 4, "43": 3, "44": 2, "45": 1 },
    badge: "New",
    description: "CloudTec® cushioning meets slide-on convenience. The most comfortable slide you'll ever wear.",
    emoji: "🖤"
  },
  {
    id: 14,
    name: "Crocs Classic Clog",
    brand: "Crocs",
    category: "Slides",
    price: 55,
    colors: ["Gray", "Pink", "Purple", "Beige"],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "36": 3, "37": 3, "38": 4, "39": 5, "40": 5, "41": 4, "42": 3, "43": 2, "44": 2, "45": 1 },
    badge: "Hot",
    description: "The iconic Crocs Classic Clog. Lightweight, odour-resistant, and loved worldwide.",
    emoji: "🩶"
  },
  {
    id: 15,
    name: "Crocs Kids Character Clog",
    brand: "Crocs",
    category: "Slides",
    price: 40,
    colors: ["Cars/Red", "Hello Kitty/Pink"],
    sizes: ["24", "26", "28", "30", "32", "34"],
    availability: { "24": 3, "26": 4, "28": 5, "30": 4, "32": 3, "34": 2 },
    badge: "Kids",
    description: "Fun character clogs kids love — Cars and Hello Kitty editions available.",
    emoji: "🚗"
  },
  {
    id: 16,
    name: "Nike Victori One Slide",
    brand: "Nike",
    category: "Slides",
    price: 45,
    colors: ["Red", "White", "Sage Green"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    availability: { "38": 3, "39": 4, "40": 5, "41": 5, "42": 4, "43": 3, "44": 2, "45": 2 },
    badge: "",
    description: "Soft foam footbed for all-day comfort. Classic Nike Swoosh on the strap.",
    emoji: "❤️"
  },
  {
    id: 17,
    name: "Crocs Literide 360 Clog",
    brand: "Crocs",
    category: "Slides",
    price: 65,
    colors: ["Black", "White", "Navy"],
    sizes: ["37", "38", "39", "40", "41", "42", "43", "44"],
    availability: { "37": 2, "38": 3, "39": 4, "40": 5, "41": 4, "42": 3, "43": 2, "44": 1 },
    badge: "",
    description: "LiteRide foam footbed is 40% lighter and 25% softer than standard Croslite foam.",
    emoji: "🖤"
  },

  // ── T-SHIRTS ──
  {
    id: 18,
    name: "Gymshark Oversized T-Shirt",
    brand: "Gymshark",
    category: "T-Shirts",
    price: 55,
    colors: ["Black", "Blue", "Gray"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 6, "L": 5, "XL": 3, "XXL": 2 },
    badge: "Hot",
    description: "Relaxed oversized fit. Soft heavyweight fabric with subtle Gymshark logo. Perfect for gym and street.",
    emoji: "🖤"
  },
  {
    id: 19,
    name: "Gymshark Crest Graphic Tee",
    brand: "Gymshark",
    category: "T-Shirts",
    price: 58,
    colors: ["Black", "Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    availability: { "S": 3, "M": 5, "L": 5, "XL": 4, "XXL": 2 },
    badge: "",
    description: "London Regent Street graphic. Bold Gymshark branding on a premium heavyweight tee.",
    emoji: "🖤"
  },
  {
    id: 20,
    name: "On Running Performance Tee",
    brand: "On Running",
    category: "T-Shirts",
    price: 65,
    colors: ["Army/Olive", "Beige/Cream", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 1, "S": 3, "M": 5, "L": 4, "XL": 3, "XXL": 1 },
    badge: "New",
    description: "Technical performance tee with moisture-wicking fabric and minimal On logo. Understated and refined.",
    emoji: "🪖"
  },
  {
    id: 21,
    name: "Nike Graphic Tee",
    brand: "Nike",
    category: "T-Shirts",
    price: 50,
    colors: ["White/Green Print", "Black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 6, "L": 5, "XL": 3, "XXL": 2 },
    badge: "Trending",
    description: "Bold Nike graphic print tee. A must-have streetwear staple.",
    emoji: "🤍"
  },
  {
    id: 22,
    name: "Nike Everyday Tee",
    brand: "Nike",
    category: "T-Shirts",
    price: 40,
    colors: ["Green", "Blue", "White", "Black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 3, "S": 5, "M": 7, "L": 6, "XL": 4, "XXL": 3 },
    badge: "",
    description: "Classic Nike logo tee in multiple colourways. Everyday comfort, everyday style.",
    emoji: "💚"
  },
  {
    id: 23,
    name: "Essentials Heavyweight Tee",
    brand: "Fear of God Essentials",
    category: "T-Shirts",
    price: 85,
    colors: ["Beige/Cream", "Black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 1, "S": 2, "M": 4, "L": 3, "XL": 2, "XXL": 1 },
    badge: "Premium",
    description: "FOG Essentials boxy oversized tee with rubberized text logo. Luxury streetwear.",
    emoji: "🤎"
  },
  {
    id: 24,
    name: "Vans Off The Wall Tee",
    brand: "Vans",
    category: "T-Shirts",
    price: 42,
    colors: ["Orange/Brown", "White", "Black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 5, "L": 5, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Vintage-style Vans graphic tee. Off the wall since 1966.",
    emoji: "🧡"
  },
  {
    id: 25,
    name: "Jordan Heritage Tee",
    brand: "Jordan",
    category: "T-Shirts",
    price: 60,
    colors: ["Gray", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    availability: { "S": 2, "M": 4, "L": 5, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Oversized Jordan Jumpman tee with heritage feel and premium cotton.",
    emoji: "🩶"
  },
  {
    id: 26,
    name: "Heaven Is Crying Graphic Tee",
    brand: "Shoo Exclusive",
    category: "T-Shirts",
    price: 45,
    colors: ["White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    availability: { "S": 3, "M": 5, "L": 4, "XL": 3, "XXL": 1 },
    badge: "Exclusive",
    description: "Bold statement graphic tee. \"Heaven Is Crying For Justice\" print.",
    emoji: "🤍"
  },
  {
    id: 27,
    name: "Gymshark Tank Top",
    brand: "Gymshark",
    category: "T-Shirts",
    price: 40,
    colors: ["Gray", "Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 6, "L": 5, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Gymshark muscle fit tank. Moisture-wicking fabric, ideal for training sessions.",
    emoji: "🩶"
  },

  // ── SHORTS ──
  {
    id: 28,
    name: "Gymshark Speed Shorts",
    brand: "Gymshark",
    category: "Shorts",
    price: 48,
    colors: ["Black", "Red", "Gray"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 6, "L": 5, "XL": 3, "XXL": 2 },
    badge: "Hot",
    description: "Lightweight, breathable training shorts. Deep side pockets and adjustable waistband.",
    emoji: "🖤"
  },
  {
    id: 29,
    name: "Nike Dri-FIT Training Shorts",
    brand: "Nike",
    category: "Shorts",
    price: 42,
    colors: ["Black", "Gray", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 3, "M": 5, "L": 4, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Nike Dri-FIT technology wicks sweat away. Elastic waistband for a secure fit.",
    emoji: "🖤"
  },
  {
    id: 30,
    name: "On Running Lightweight Shorts",
    brand: "On Running",
    category: "Shorts",
    price: 70,
    colors: ["Black", "Gray", "Olive"],
    sizes: ["XS", "S", "M", "L", "XL"],
    availability: { "XS": 1, "S": 3, "M": 4, "L": 3, "XL": 2 },
    badge: "New",
    description: "Ultra-lightweight On Running shorts with integrated liner. Built for running performance.",
    emoji: "🖤"
  },
  {
    id: 31,
    name: "Jordan Fleece Shorts",
    brand: "Jordan",
    category: "Shorts",
    price: 55,
    colors: ["Black", "Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    availability: { "S": 2, "M": 4, "L": 5, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Cozy Jordan fleece shorts with embroidered Jumpman logo.",
    emoji: "🩶"
  },
  {
    id: 32,
    name: "Gymshark Sport Shorts",
    brand: "Gymshark",
    category: "Shorts",
    price: 45,
    colors: ["Navy", "Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 6, "L": 5, "XL": 3, "XXL": 1 },
    badge: "",
    description: "Versatile Gymshark sport shorts. Great for gym or casual wear.",
    emoji: "🔵"
  },

  // ── PANTS ──
  {
    id: 33,
    name: "Nike Cream Joggers",
    brand: "Nike",
    category: "Pants",
    price: 75,
    colors: ["Cream/White", "Black", "Gray"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 1, "S": 3, "M": 5, "L": 4, "XL": 3, "XXL": 2 },
    badge: "New",
    description: "Nike tech fleece joggers with tapered fit. Embroidered Swoosh, side zip pockets.",
    emoji: "🤍"
  },
  {
    id: 34,
    name: "On Running Track Pants",
    brand: "On Running",
    category: "Pants",
    price: 120,
    colors: ["Black", "Navy", "Olive"],
    sizes: ["XS", "S", "M", "L", "XL"],
    availability: { "XS": 1, "S": 2, "M": 4, "L": 3, "XL": 2 },
    badge: "Premium",
    description: "Technical On Running track pants. Lightweight with tapered leg and On branding.",
    emoji: "🖤"
  },
  {
    id: 35,
    name: "Gymshark Crest Track Pants",
    brand: "Gymshark",
    category: "Pants",
    price: 65,
    colors: ["Black", "Gray", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 3, "M": 5, "L": 4, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Gymshark crest logo joggers. Warm, flexible, and stylish.",
    emoji: "🖤"
  },
  {
    id: 36,
    name: "Adidas Tiro Track Pants",
    brand: "Adidas",
    category: "Pants",
    price: 60,
    colors: ["Black/White", "Navy/White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 4, "M": 5, "L": 4, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Adidas Tiro 23 track pants. Three-stripe classic with tapered fit.",
    emoji: "🖤"
  },

  // ── OUTERWEAR ──
  {
    id: 37,
    name: "On Running Half-Zip",
    brand: "On Running",
    category: "Outerwear",
    price: 130,
    colors: ["Beige/Khaki", "Black", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 1, "S": 2, "M": 4, "L": 3, "XL": 2, "XXL": 1 },
    badge: "New",
    description: "On Running Climate half-zip. Insulated yet breathable for training in any weather.",
    emoji: "🤎"
  },
  {
    id: 38,
    name: "Gymshark Long Sleeve Top",
    brand: "Gymshark",
    category: "Outerwear",
    price: 55,
    colors: ["Navy", "Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    availability: { "XS": 2, "S": 3, "M": 5, "L": 4, "XL": 3, "XXL": 2 },
    badge: "",
    description: "Slim-fit Gymshark long sleeve. Moisture-wicking for year-round training.",
    emoji: "🔵"
  },
  {
    id: 39,
    name: "On Running Jacket",
    brand: "On Running",
    category: "Outerwear",
    price: 195,
    colors: ["Black", "Olive", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    availability: { "XS": 1, "S": 2, "M": 3, "L": 2, "XL": 1 },
    badge: "Premium",
    description: "On's signature weather jacket. Wind and water resistant. Built for runners.",
    emoji: "🖤"
  },

  // ── CAPS ──
  {
    id: 40,
    name: "NY Yankees Cap",
    brand: "New Era",
    category: "Caps",
    price: 45,
    colors: ["Green/Gold", "Navy/White", "Black"],
    sizes: ["One Size"],
    availability: { "One Size": 8 },
    badge: "Hot",
    description: "New Era 9Forty NY Yankees cap. Adjustable strap, structured crown.",
    emoji: "🟢"
  },
  {
    id: 41,
    name: "LA Dodgers Cap",
    brand: "New Era",
    category: "Caps",
    price: 45,
    colors: ["Black/White", "Royal Blue"],
    sizes: ["One Size"],
    availability: { "One Size": 6 },
    badge: "",
    description: "New Era 9Forty LA Dodgers cap. Classic baseball styling.",
    emoji: "🖤"
  },
  {
    id: 42,
    name: "Nike Heritage Bucket Hat",
    brand: "Nike",
    category: "Caps",
    price: 38,
    colors: ["Red", "Sage/White", "Black"],
    sizes: ["One Size"],
    availability: { "One Size": 7 },
    badge: "Trending",
    description: "Nike swoosh bucket hat. Wide brim for sun protection with style.",
    emoji: "❤️"
  },
  {
    id: 43,
    name: "Jordan Jumpman Cap",
    brand: "Jordan",
    category: "Caps",
    price: 42,
    colors: ["Black", "White", "Gray"],
    sizes: ["One Size"],
    availability: { "One Size": 5 },
    badge: "",
    description: "Jordan brand snapback with embroidered Jumpman logo.",
    emoji: "🖤"
  }
];
